query GetConfirmedQualifications($languageCode: LanguageCodeIso!, $zone: Zone!, $isUnifiedSite: Boolean!) {
  viewer {
    _id
    confirmedQualifications: qualifications(
      includeVerified: true
      status: confirmed
      languageCode: $languageCode
      zone: $zone
      isUnifiedSite: $isUnifiedSite
      platform: WEB
      source: PROFILE
    ) {
      ...qualification
      __typename
    }
    __typename
  }
}

fragment qualification on Qualification {
  id
  name {
    text
    ontologyId
    __typename
  }
  institute {
    text
    ontologyId
    __typename
  }
  completed
  completionDate {
    ... on Year {
      year
      __typename
    }
    ... on MonthYear {
      month
      year
      __typename
    }
    __typename
  }
  formattedCompletion
  highlights
  status
  verificationUrl
  credential {
    credentialInfo {
      name
      values
      __typename
    }
    manageVerificationUrl
    deleteVerificationUrl
    __typename
  }
  __typename
}
