query jobDetailsWithPersonalised(
  $jobId: ID!
  $jobDetailsViewedCorrelationId: String!
  $sessionId: String!
  $zone: Zone!
  $locale: Locale!
  $languageCode: LanguageCodeIso!
  $countryCode: CountryCodeIso2!
  $timezone: Timezone!
  $enableGetCandidateJobMatch: Boolean!
  $platform: Platform!
  $visitorId: UUID!
) {
  jobDetails(
    id: $jobId
    tracking: { channel: "WEB", jobDetailsViewedCorrelationId: $jobDetailsViewedCorrelationId, sessionId: $sessionId }
  ) {
    ...job
    ...jobPersonalised
    workArrangements(visitorId: $visitorId, channel: "JDV", platform: WEB) {
      arrangements {
        type
        label(locale: $locale)
        __typename
      }
      label(locale: $locale)
      __typename
    }
    insights {
      ... on ApplicantCount {
        volumeLabel(locale: $locale)
        count
        __typename
      }
      __typename
    }
    __typename
  }
}

fragment badges on JobDetails {
  badges(visitorId: $visitorId, platform: WEB, locale: $locale) {
    badges {
      badge
      displayText(locale: $locale)
      ... on JobDetailsInteractiveBadge {
        message(locale: $locale, zone: $zone)
        __typename
      }
      ... on JobDetailsResponsiveHirerBadge {
        message(locale: $locale, zone: $zone)
        badgeScore
        badge
        displayText(locale: $locale)
        __typename
      }
      __typename
    }
    __typename
  }
  __typename
}

fragment job on JobDetails {
  job {
    sourceZone
    tracking {
      adProductType
      classificationInfo {
        classificationId
        classification
        subClassificationId
        subClassification
        __typename
      }
      hasRoleRequirements
      isPrivateAdvertiser
      locationInfo {
        area
        location
        locationIds
        __typename
      }
      workTypeIds
      postedTime
      __typename
    }
    id
    title
    phoneNumber
    isExpired
    expiresAt {
      dateTimeUtc
      __typename
    }
    isLinkOut
    contactMatches {
      type
      value
      __typename
    }
    isVerified
    abstract
    content(platform: WEB)
    status
    listedAt {
      label(context: JOB_POSTED, length: SHORT, timezone: $timezone, locale: $locale)
      dateTimeUtc
      __typename
    }
    salary {
      currencyLabel(zone: $zone)
      label
      __typename
    }
    shareLink(platform: WEB, zone: $zone, locale: $locale)
    workTypes {
      label(locale: $locale)
      __typename
    }
    advertiser {
      id
      name(locale: $locale)
      isVerified
      registrationDate {
        dateTimeUtc
        __typename
      }
      __typename
    }
    location {
      label(locale: $locale, type: LONG)
      __typename
    }
    classifications {
      label(languageCode: $languageCode)
      __typename
    }
    products {
      branding {
        id
        cover {
          url
          __typename
        }
        thumbnailCover: cover(isThumbnail: true) {
          url
          __typename
        }
        logo {
          url
          __typename
        }
        __typename
      }
      bullets
      questionnaire {
        questions
        __typename
      }
      video {
        url
        position
        __typename
      }
      displayTags {
        label(locale: $locale)
        __typename
      }
      __typename
    }
    __typename
  }
  ...badges
  companyProfile(zone: $zone) {
    id
    name
    companyNameSlug
    shouldDisplayReviews
    branding {
      logo
      __typename
    }
    overview {
      description {
        paragraphs
        __typename
      }
      industry
      size {
        description
        __typename
      }
      website {
        url
        __typename
      }
      __typename
    }
    reviewsSummary {
      overallRating {
        numberOfReviews {
          value
          __typename
        }
        value
        __typename
      }
      __typename
    }
    perksAndBenefits {
      title
      __typename
    }
    __typename
  }
  companySearchUrl(zone: $zone, languageCode: $languageCode)
  companyTags {
    key(languageCode: $languageCode)
    value
    __typename
  }
  restrictedApplication(countryCode: $countryCode) {
    label(locale: $locale)
    __typename
  }
  sourcr {
    image
    imageMobile
    link
    __typename
  }
  __typename
}

fragment jobPersonalised on JobDetails {
  personalised {
    isSaved
    appliedDateTime {
      shortAbsoluteLabel(locale: $locale, timezone: $timezone)
      __typename
    }
    
    topApplicantBadge2(
      visitorId: $visitorId
      platform: $platform
      languageCode: $languageCode
    ) {
      label(locale: $locale)
      description(locale: $locale, zone: $zone)
      __typename
    }
    salaryMatch {
      ... on JobProfileMissingSalaryPreference {
        label(locale: $locale)
        __typename
      }
      ... on JobProfileSalaryMatch {
        label(locale: $locale)
        salaryPreference(locale: $locale, languageCode: $languageCode) {
          id
          description
          country {
            countryCode
            name
            __typename
          }
          currencyCode
          amount
          salaryType
          __typename
        }
        __typename
      }
      ... on JobProfileSalaryNoMatch {
        label(locale: $locale)
        __typename
      }
      __typename
    }
    candidateJobMatch @include(if: $enableGetCandidateJobMatch) {
      __typename
      ... on CandidateJobMatchExists {
        createdAt
        shouldApply
        shouldApplyMessage
        summary
        recommendations
        trackingId
        __typename
      }
      ... on CandidateJobMatchInProgress {
        waitForMs
        trackingId
        __typename
      }
      ... on CandidateJobMatchResultInvalid {
        message
        __typename
      }
      ... on CandidateJobMatchNotExists {
        __typename
      }
    }
    __typename
  }
  __typename
}
