query getUserNotificationPreferenceCategories {
  getUserNotificationPreferenceCategories {
    id
    name
    userNotificationPreferences {
      id
      channel
      enabled
      __typename
    }
    __typename
  }
}
